[package]
name = "nts_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
tempfile = "3.13.0"
native-tls = "0.2"
crossterm = "0.28.1"
ratatui = "0.28.1"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'